# Generated by Django 4.2.7 on 2023-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_users_userss'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='municipality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userss',
            name='province',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Applicant', 'Applicant'), ('Employer', 'Employer')], default='Employee', max_length=10),
        ),
    ]
