# Generated by Django 4.2.7 on 2023-12-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userss_contact_number_userss_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userss',
        ),
    ]
