# Generated by Django 4.2.7 on 2023-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_skill_remove_profile_skills_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_of_Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='field_of_expertise',
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_expertise',
            field=models.ManyToManyField(blank=True, to='main.field_of_expertise'),
        ),
    ]
