# Generated by Django 4.2.7 on 2023-12-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_job_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='main.Profile'),
        ),
    ]