# Generated by Django 4.2.7 on 2023-12-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_job_post_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='employer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
