# Generated by Django 4.2.7 on 2023-12-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_job_post_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='job_post',
        ),
        migrations.DeleteModel(
            name='Job_Post',
        ),
    ]
