# Generated by Django 4.2.7 on 2023-12-12 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_job_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='employee',
        ),
        migrations.AddField(
            model_name='job_application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_post'),
        ),
    ]
