# Generated by Django 4.2.7 on 2023-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_job_application_employee_job_application_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='field_of_expertise',
            field=models.ManyToManyField(blank=True, to='main.field_of_expertise'),
        ),
        migrations.RemoveField(
            model_name='job_post',
            name='skills_recommended',
        ),
        migrations.AddField(
            model_name='job_post',
            name='skills_recommended',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
    ]
