# Generated by Django 4.2.7 on 2023-12-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_notifications_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=255),
        ),
    ]
